name: kk-sync
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  kk-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.9.3'
    - run: |
        go run ./test-go/test.go
        curl -I -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/neolit123
